# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

[[substitution]]
description = 'Add virtual keyword to Init()'
pattern = '[[nodiscard]] Liveness Init('
replace = '[[nodiscard]] virtual Liveness Init('
