# Copyright (c) 2025 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

[[substitution]]
description = 'Replacing GlobalFeatures with BraveGlobalFeatures'
pattern = 'new GlobalFeatures()'
replace = 'CreateBraveGlobalFeatures()'

[[substitution]]
description = 'Forward declare CreateBraveGlobalFeatures'
re_pattern = '(namespace {)'
replace = 'GlobalFeatures* CreateBraveGlobalFeatures();\n\1'
